### PR TITLE
Add summary-report logging

### LINKED ISSUE #6: Add logging for summary-report.py
Add logging to summary-report.py. Some suggestions:
- Log the start and end of script
- Log the number of jobs that failed. If no jobs failed, then log that.

### PR DESCRIPTION
**Pull request by DefCon-007**
Fixes #6

### CODE REVIEW

**Comment by DefCon-007** [comment]
@sumeshpremraj The travis CIis failing due some internal error not because some propblem in my script. Please review the PR

**Comment by sumeshpremraj** [comment]
@DefCon-007 you can ignore the Travis error (that's due to some misconfiguration). But there's some conflicts caused by my accepting a PR that was filed before yours, please resolve them.

**Comment by DefCon-007** [comment]
@sumeshpremraj : Done

**Comment by sumeshpremraj** [comment]
@DefCon-007 the autodetect SMTP port commit looks great.

Couple of suggestions for the logging commit:
- Log to a more predictable location like /var/log/summary-report.log
- Use logging module instead of your own implementation, since that is built-in and would make your code cleaner and easier to understand

**Review by sumeshpremraj — APPROVED** [review]

**Pull request merged**
